### ISSUE TITLE
Detailed readme of gcps

### ISSUE THREAD

**Issue by aman00323** [daftcreations/gcps#2]
Currently, our package doesn't hold any documentation regarding how to use it. we need a few basic things which are described below.

- A logo that represents our package ability. 

- Write a well-documented README that can be used easily.

**Comment by pratikbin** [comment]
Suggesting adding the simplest ways to install, like I did [here](https://github.com/pratikbin/go-nproc/#install), where release artifact names based on OS and arch that can easily identifiable with `uname`. This will work in case of most non windows and almost all unix based OS But in that case of windows won't work cause that's another universe of CLI things

**Comment by pratikbin** [comment]
Logo remain

**Comment by aman00323** [comment]
@pratikbin closing this issue
