### ISSUE TITLE
Required changes needed due to org change

### ISSUE THREAD

**Issue by Naman2706** [daftcreations/gcps#23]
- fix the readme. (curl cmd)
- change the username that has been used inside the code and change it with the org name 
- other required changes

**Comment by pratikbin** [comment]
For curl we'll be going to use other tool. I need your help with testing int in windows @Naman2706

**Comment by Naman2706** [comment]
okay how can i help ? @pratikbin

**Comment by pratikbin** [comment]
> change the username that has been used inside the code and change it with the org name

Can you do that? and what other changes required ?
